### PR TITLE
Fix bug

### PR DESCRIPTION
**Pull request by IntegratedQuantum**
Just after I downloaded the game I encountered the following bug when clicking on start:
java.lang.NullPointerException
	at io.cubz.blocks.BlockInstance.getMesh(BlockInstance.java:56)
	at io.cubz.blocks.BlockSpatial.<init>(BlockSpatial.java:10)
	at io.cubz.blocks.BlockInstance.getSpatial(BlockInstance.java:106)
	at io.cubz.world.chunk.Chunk.generateFrom(Chunk.java:52)
	at io.cubz.world.LocalWorld.plymove(LocalWorld.java:105)
	at io.cubz.logic.Cubz.update(Cubz.java:314)
	at org.jungle.game.Game.update(Game.java:84)
	at org.jungle.game.Game.loop(Game.java:58)
	at org.jungle.game.Game.start(Game.java:32)
	at io.cubz.main.GameLauncher.main(GameLauncher.java:34)

I traced the bug to registerBlocks which was never called and left all blocks null resulting in this error.

### CODE REVIEW

**Comment by zenith391** [comment]
First of all, thanks for having interest in this project.
The bug you found is a real bug, homewer the patch you proposed should have taken account of the ModLoader, which seems to be the initial cause of the bug. I will try to find a clean patch, post it, and mention you.
Thanks a lot for trying to help Cubz, i really like that, continue if you find more bugs or even if you have a feature request.

**Comment by zenith391** [comment]
Note: If you want to test the game (a older version), you can use [the launcher](https://github.com/MunirkSoft/Cubz/releases/tag/cl1.0.1)

**Comment by IntegratedQuantum** [comment]
I thought putting it into the constructor of BlockRegistry would be a better solution because then it is certain the BlockRegistry is always properly initialized.

**Comment by CristeaAndreiFlavian** [comment]
Thank you anyways for trying and help us 😄

**Comment by zenith391** [comment]
It is certain, but it's against how modding works in the game

**Comment by IntegratedQuantum** [comment]
how does it work then?

**Comment by zenith391** [comment]
Here how it works:
On startup, Cubz class will search for any classes being a mod using the Reflections library.
For each mod, it will call ModLoader.init method with it in argument
It will then do some things, and at some points it will call any methods with a `@EventHandler` annotation that has a matching type. Types are directly found in the file and depend on the current operation (registering blocks or items, or just initing).

And so, the bug (that seems to only happen in some [unknown] cases only), will prevent one of the steps to get executed correctly. And will result in the blocks being not registered.

**Comment by IntegratedQuantum** [comment]
I now found out that the bug was created by
Failed to load class org.slf4j.impl.StaticLoggerBinder
which I overlooked.
I could solve it by adding the slf4j-simple.jar.

**Pull request closed without merging**
